# Generated by Django 5.1.3 on 2024-11-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('types', models.CharField(max_length=255)),
                ('capacity', models.FloatField()),
                ('location', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
    ]
